### ISSUE TITLE
Poslati jedan zahtjev za sve glave kaznenog zakona

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/crimemap#2]
Barbara

**Comment by schlos** [comment]
[Biljeske sa sastanka]

Barbara - slanje jednog requesta koji uključuje sve glave Kaznenog zakona, do kraja tjedna

**Comment by barbara2312** [comment]
Poslano 25.1.

**Comment by schlos** [comment]
@barbara2312 neka stoji in progress dok ne stigne odgovor. kad stigne mozemo zatvoriti (status Done na waffle)

**Comment by schlos** [comment]
Odgovoreno s podacima po policijskim upravama:
http://imamopravoznati.org/request/broj_svih_kaznenih_djela_prikaza

Sljedece: 
Traziti podatke po policijskim postajama (@ LanaPdg)
